stolostron/build-harness-extensions

modules/release-ff/Configfile
modules/release-ff/Makefile
modules/release-ff/bin/release_ff.sh

A participating repo should lay down a file named `RELEASE_FF_BRANCH` in the root of their project and have it contain the name of the branch of their repo they would like to fast-forward their changes from master into.

Implement configurable release fast-forwarding

---

modules/release-ff/Configfile
modules/release-ff/Makefile
modules/release-ff/bin/release_ff.sh

Same as last time, except - we need to look for the configfile within the build harness extensions directory, not the repo's own directory.  I had a residual one locally which is why my tests succeeded when a real development build failed even though it wasn't interacting with release-ff.
A participating repo should lay down a file named RELEASE_FF_BRANCH in the root of their project and have it contain the name of the branch of their repo they would like to fast-forward their changes from master into.

Implement configurable release fast-forwarding, take 2

---

modules/deploy/Makefile
modules/jq/Makefile
modules/retag/Makefile

These should not always report an error. If we do not need to use them, we do not need to know about the error. 
If we want to catch the error, we should check for existence of the commands before we try to use them so that we can present a useful error message.

prevent unneeded errors from bubbling up

---

modules/sonar/Makefile

In the case that no potential vulnerabilities are found by Gosec, it will not create the gosec.json file that  sonar-scanner expects, causing the scanner to halt and consequently that rule will fail.
By removing the --quiet parameter, an empty issue array will be created in the gosec.json file so that things move on interrupted.

Remove quiet parameter from Gosec Call

---

modules/pipeline-manifest/Makefile
modules/pipeline-manifest/bin/decorate-manifest.sh

As we prepare for snapshotting, send in the image-alias dictionary and use it at quay-retag time.

Decorate new-format of manifest

---

modules/pipeline-manifest/Makefile
modules/pipeline-manifest/bin/parser.py
modules/pipeline-manifest/bin/postprocess.sh

We need the ability to tag everything in a (git) repo with a particular release tag, such as `v1.0` rather than individual components' versions and SNAPSHOT/date.  This gives us a particular target to call: `pipeline-manifest/_retag` to do just that.
Required to be specified:  
`PIPELINE_MANIFEST_FILE_NAME`  (without .json suffix)
`TAG` (if it starts with `20`, we assume it's a date and do the old-style decoration)
`PIPELINE_MANIFEST_RETAG_REPO` (literal text: `git` or `quay`)
The parser now accepts both v1 and v2 style manifests.

Add ability to tag all repo elements with a version as well as snapshot name

---

modules/sonar/Makefile

use below env to skip `test/e2e` package.
```
export SONAR_GO_TEST_ARGS="\`go list ./... | grep -v test/e2e\`"
``` 
This allow us removing the `// +build integration` tag in e2e source file.
Because tag is cause e2e/test package not being built and can't debug in vscode

Support SONAR_GO_TEST_ARGS

---

modules/pipeline-manifest/Makefile
modules/pipeline-manifest/bin/get-latest-manifest.sh

As a convenience - add the ability to dig out the "latest" manifest from snapshots from a given branch and release

Add ability to find the latest manifest for a given release and branch

---

modules/clusterpool/Makefile
modules/oc/Makefile

This change will cause the `oc` module to use a kubeconfig in the vendor directory.  We've included a new helpful clusterpool target to capture the final consumer use-case of clusterpool (listing ClusterDeployments) now that the clusterpool module will no longer connect your global kubeconfig to the clusterpool host.  
These changes were spurred on by a recent incident where a build harness clusterpool target changed a user's primary kubecontext globally for their system during an ACM deploy.  The ACM deploy successfully retargetted to the clusterpool host and resulted in an unrecoverable conflict between hive running on the clusterpool host and the version of hive shipped with ACM.  This vendorized kubeconfig will prevent any future overwrites of the global kubeconfig/kubecontext by the …

Vendorize the Kubeconfig used in the oc module to prevent Kubeconfig polluiton.

---

modules/clusterpool/Makefile
modules/clusterpool/templates/clusterclaim.nolifetime.yaml.template

Implements https://github.com/open-cluster-management/backlog/issues/5959
Specification of lifetime is a string, purportedly similar to:
```
CLUSTERPOOL_LIFETIME=5m
CLUSTERPOOL_LIFETIME=1h
```
If present in the environment, the `lifetime` parameter is added to the ClusterClaim yaml.

Add a lifetime parameter to cluster claims

---

modules/oc/Makefile

Unbeknownst to us, the `oc` directory in https://mirror.openshift.com/pub/openshift-v4/clients/oc was taken to the woodshed... so we need to patch *everything*.

Patch OC_SOURCE_URL to use ocp subdirectory rather than the oc directory

---

modules/clusterpool/Makefile
modules/clusterpool/templates/clusterclaim.nolifetime.yaml.template
modules/clusterpool/templates/clusterclaim.yaml.template

Implements issue https://github.com/open-cluster-management/backlog/issues/7585
`unset CLUSTERPOOL_GROUP_NAME`:
```
kind: ClusterClaim
metadata:
name: david-claim-deleteme
namespace: clusterpool
spec:
clusterPoolName: canary-aws-4427
lifetime: 1h
subjects:
- kind: Group
apiGroup: rbac.authorization.k8s.io
name: 'system:mastsers'
```
`export CLUSTERPOOL_GROUP_NAME=nonesuch:nonesuch`
`unset CLUSTERPOOL_LIFETIME`:
```
apiVersion: hive.openshift.io/v1
kind: ClusterClaim
metadata:
name: david-claim-deleteme2
namespace: clusterpool
spec:
clusterPoolName: canary-aws-4428
subjects:
- kind: Group
apiGroup: rbac.authorization.k8s.io
name: 'nonesuch:nonesuch'
```

Parameterize RBAC group name

---

modules/clusterpool/Makefile
modules/clusterpool/templates/clusterclaim.subjects.serviceaccount.yaml.template

This PR includes some new conditional logic in clusterclaim creation focused on serviceaccounts.  If the calling user is a serviceaccount on the target kube cluster, they will be automatically added to the `subjects` array of the clusterclaim.  If the user is a non-serviceaccount user, they can set `CLUSTERPOOL_SERVICE_ACCOUNT` and that string will be added as a subject on the claim.  A serviceaccount cannot add other serviceaccounts to its claim in this use case, RBAC groups or service account groups should be used instead.  
If you need access to a serviceaccount with which to test these changes before merging them, please contact me.

Add service account support to the clusterpool module

---

modules/release-ff/bin/release_ff.sh

Updates the release-ff module to work with variables `GITHUB_USER` and `GITHUB_TOKEN`. This way an SSH key is not required (which is not possible in Travis for public repos).
An example in action using a copy of the updated script:
https://travis-ci.com/github/open-cluster-management/application-chart/jobs/485339301#L145
One potential issue is that if a repo already has `GITHUB_TOKEN` set up, but it is not an administrator token, `release-ff` will stop working. We could add a 3rd variable to opt in to token-based authentication.

Support GITHUB_USER and GITHUB_TOKEN Travis vars

---

modules/bootstrap-ks/Makefile

Change the default bootstrap-ks branch name from master to main to accomodate changes in that repo.

Change default bootstrap-ks branch from master to main

---

modules/sonar/Makefile

In the newest version of gosec, the `-fmt` option is ignored if there isn't a `-out` option.

fix output of gosec scanner

---

modules/bootstrap-ks/Makefile

This PR adds 3 ARO-specific targets:
* `bootstrap-ks/aro-install` - deploys an ARO cluster using [bootstrap-ks](https://github.com/open-cluster-management/bootstrap-ks)
* `bootstrap-ks/aro-save-secret` - save an ARO cluster provisioned by [bootstrap-ks](https://github.com/open-cluster-management/bootstrap-ks) as a secret on a kubernetes cluster
* `bootstrap-ks/aro-delete-cluster` - destroys an ARO cluster provisioned by [bootstrap-ks](https://github.com/open-cluster-management/bootstrap-ks)
This PR also adds another target to get a new field in the ARO secret:
* `bootstrap-ks/get-cluster-json` - gets the json field value from a secret
This PR also updates a few targets:
* `bootstrap-ks/get-cluster-kubeconfig` will now generate a kubeconfig by logging in with credentials if no kubeconfig …

Add support for provisioning, saving as secrets, and getting metadata from ARO clusters via bootstrap-ks

---

modules/bootstrap-ks/Makefile

This PR adds 3 ROSA-specific targets:
* `bootstrap-ks/rosa-install` - deploys an ROSA cluster using [bootstrap-ks](https://github.com/open-cluster-management/bootstrap-ks)
* `bootstrap-ks/rosa-save-secret` - save an ROSA cluster provisioned by [bootstrap-ks](https://github.com/open-cluster-management/bootstrap-ks) as a secret on a kubernetes cluster
* `bootstrap-ks/rosa-delete-cluster` - destroys an ROSA cluster provisioned by [bootstrap-ks](https://github.com/open-cluster-management/bootstrap-ks)
This PR also adds another target to get a new field in the ROSA secret:
* `bootstrap-ks/get-cluster-json` - gets the json field value from a secret
This PR also updates a few targets:
* `bootstrap-ks/get-cluster-kubeconfig` will now generate a kubeconfig by logging in with credentials if no …

Add support for provisioning, saving as secrets, and getting metadata from ROSA clusters via bootstrap-ks

---

modules/clusterpool/Makefile
modules/clusterpool/templates/clusterclaim.nolifetime.yaml.template
modules/clusterpool/templates/clusterclaim.yaml.template

To adapt to the auto-import claimed clusters from ACM 2.4, we need to include the flag to disable auto-import, and a way to set it!  
We'll default to false!

Add auto import toggle to checkout, defaulting to false

---

modules/clusterpool/templates/clusterclaim.nolifetime.yaml.template
modules/clusterpool/templates/clusterclaim.yaml.template

This PR fixes the annotation used to skip ACM 2.4's auto-import (disabling auto-import by default to avoid breaking changes).

Correct the annotation used to skip auto-import on clusterclaim

---

modules/clusterpool/Makefile
modules/clusterpool/bin/checkout-poll.sh
modules/clusterpool/bin/checkout-two.sh
modules/clusterpool/bin/verify-status.sh

This involves two big changes:  multithreading and rendezvous of cluster checkouts, and for those checkouts - we need to define a unique place for them to drop their metadata files, as they all assume `.` is the place.

Enable checking out two clusters simultaneously for canaries

---

modules/osci/bin/osci_publish.sh

This changes the echo for the git clone to not include secrets and aborts if this clone of the pipeline repo fails.
Context on this the secret passing is failing in the prow step registry for the step I made. I have some concerns about the secrets leaking with the existing echo. Related PR: https://github.com/openshift/release/pull/25671

ocsi_publish.sh: Abort on failing git clone for pipeline repo

---

modules/sonar/Makefile

The background is that I discovered Prow fetches commits manually but doesn't appear to collect references SonarCloud needs, for example here were the image build commands from my test repo for a PR:
```shell
mkdir -p /go/src/github.com/${REPO_OWNER}/${REPO_NAME}
git init
git config user.name ci-robot
git config user.email ci-robot@openshift.io
git fetch https://github.com/${REPO_OWNER}/${REPO_NAME}.git --tags --prune
git fetch https://github.com/${REPO_OWNER}/${REPO_NAME}.git ${BASE_BRANCH_HASH}
git checkout ${BASE_BRANCH_HASH}
git branch --force ${PULL_BASE_REF} ${BASE_BRANCH_HASH}
git checkout ${PULL_BASE_REF}
git fetch https://github.com/${REPO_OWNER}/${REPO_NAME}.git ${PR_BRANCH_HASH}
GIT_AUTHOR_DATE=1644630248 GIT_COMMITTER_DATE=1644630248 git merge --no-ff ${PR_BRANCH_HASH}
git …
```

Fetch and rebase branch for SonarCloud

---

modules/sonar/Makefile

When rebasing, signal that the PR commits have precedence for conflicts. These commits are 'theirs' and not 'ours' because rebase is from the perspective of the branch being rebased on.

sonar: Use rebase strategy 'theirs'

---

modules/sonar/Makefile

Assuming it's a safe assumption that the default branch is always `main`, this will override PRs in `release` so that the rehearsal scans pass (assuming the SonarCloud scan passes).

Always run a `postsubmit` scan in `release`

---

modules/sonar/Makefile

I realized by defaulting to `main`, it may be oversimplifying and do strange things to Sonar scans when a `release-*` branch is actually being scanned. This instead digs through the Prow job spec to grab the target branch.
References:
- Pod/cloning configuration: https://github.com/kubernetes/test-infra/blob/master/prow/pod-utilities.md#how-to-configure
- Prow variables: https://github.com/kubernetes/test-infra/blob/master/prow/jobs.md#job-environment-variables
Followup to:
- #173

Use target branch instead of `main`

---

modules/sonar/Makefile

When the forked branch has exactly the same name, the rebase fails and then runs a scan with zero changes:
```
fatal: A branch named 'release-2.4' already exists.
```
This should fix this collision. Since we set the `sonar.pullrequest.branch` manually for SonarCloud, I don't think the name difference should affect the scan result, but I'll test that out.
Identified in PR:
- https://github.com/stolostron/grc-ui/pull/901
- [Sonar logs](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/stolostron_grc-ui/901/pull-ci-stolostron-grc-ui-release-2.4-lint-unittest-sonarcloud/1545426724504735744/artifacts/test/build-log.txt)

Prevent branch name conflicts in SonarCloud

---

modules/sonar/Makefile

Followup to:
- #176 
The original code was printing the target branch name instead of the PR number.

Fix PR number reference

---

modules/osci/Makefile
modules/osci/bin/osci_publish.sh

Find more details on this issue [here](https://github.com/stolostron/backlog/issues/24890) and [here](https://github.com/stolostron/backlog/issues/24967) but...
In summary - the issue involves a difference in the generation of quay.io destination image tags between the `ocm-ci-image-mirror` OSCI/Prow workflow and the tag pushed to the [pipeline](https://github.com/stolostron/pipeline/tree/2.6-integration) manifest.  
The `ocm-ci-image-mirror` workflow mirrors the built image from the CI registry by sha to quay.io and versions it as `<Z_RELEASE_VERSION-from-release-repo>-<git-sha>`.  The `osci/publish` target in the [BHE](https://github.com/stolostron/build-harness-extensions) versions the destination tag (the tag used in quay.io/stolostron) using the COMPONENT_VERSION from the repo of the …

Patch a version mismatch between the osci/publish tag and ocm-ci-image-mirror destination tag

---

modules/pipeline-manifest/Makefile

Turns out, when components publish to the pipeline, they correctly version the image-tag by the new Z_RELEASE_VERSION-GIT_SHA tag, but the _osci_to_quay doesn't mirror the image to this tag (I just now discovered this), instead, it queries the image-version entry in the manifest and uses that version for both the floating tag pull from the CI registry and the tag construction, so we end up with the X.Y release version tag mirrored but a reference to the X.Y.Z. 
Good news is - the fix is simple.  We'll ask the mirror to use the full destination tag from image-tag in the manifest and we're good to go.

Use image tag as mirror dest

---

modules/pipeline-manifest/bin/_backplane_mirror_index.sh

Temporarily exclude klusterlet operator bundle from mce 2.2 builds. Klusterlet _should_ already be excluded from acm 2.7 because of [this](https://github.com/stolostron/build-harness-extensions/blob/main/modules/pipeline-manifest/bin/_mirror-index.sh#:~:text=%23%20Call%20make_index%20with%20klusterlet,fi), unless it is re-introduced in a different spot.

Temporarily exclude klusterlet operator bundle from mce 2.2 builds

---

modules/pipeline-manifest/bin/_mirror-index.sh

Due to the floating tag updating mid fix, we ended up going with an even more recent version of postgresql13 than originally anticipated. Because of this, the "labeling" system of the mirroring needed to be updated as well to accurately reflect the logs. This is that sha update.

Re-update of postgresql13 commit

---

modules/pipeline-manifest/bin/_backplane_mirror_index.sh

Before the split of MCE from ACM, the klusterlet operator bundle needed was to be found in namespace `rhacm2`. After the split the klusterlet operator bundle needed was to be found in namespace `multicluster-engine`. This update reflects that change. This allows us to better manage klusterlet versions included in ACM and MCE.

Updates the namespace for querying klusterlet bundle versions

---

modules/pipeline-manifest/bin/_backplane_mirror_index.sh

This exclusion is (should be) no longer needed. Also happy to say it _did actually_ work in the end, taking that as a win!

Removes the temporary exclusion of klusterlet operator bundle from MCE

---

modules/pipeline-manifest/bin/_generate_downstream_manifest.py

Dist-git's old DNS name has been unceremoniously and without much notification been changed, so we need to update that URL. 
[Here's](https://chat.google.com/room/AAAA-umhJ10/C_iq6TADAR8) where we found out.

Dist-git's name has changed to https://pkgs.devel.redhat.com/cgit/

---

modules/pipeline-manifest/bin/_backplane_mirror_index.sh
modules/pipeline-manifest/bin/_mirror-index.sh

This changes migrates from using the Docker V2 API directly via `curl` to using `podman search` to list and filter tags on a given bundle image to be included in our custom catalog image.  This change was necessitated by a change in the V2 API implementation running underneath registry.redhat.io which began paginating results, omitting some critical values.  `podman search`  allows you to configure a list size limit, so we specify a limit higher than the upper bound of our expectations and search for all tags within that limit without pagination.

Migrate bundle listing logic to podman search to fix Pagination issues

---

modules/opm/Makefile

This PR adds a target and related vars to the OPM module of the build harness to generate a catalog image from a list of bundle images.

Add a target to build a catlog from a list of bundles

---

modules/sonar/Makefile

`sonar.login` is deprecated
ref: https://community.sonarsource.com/t/deprecating-sonar-login-and-sonar-password-in-favor-of-sonar-token/95829

`sonar.login` --> `sonar.token`

---

modules/oc/Makefile

Need version detection for compatibility since `oc` v4.16 is only compatible with systems that have GLIBC >=v2.32. Otherwise errors like these occur:
```
oc: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by oc)
oc: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by oc)
oc: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by oc)
```
Related to:
- https://github.com/stolostron/image-builder/pull/139

Detect GLIBC version for `oc`
