modules/yq/Makefile

Similar to jq approach - using the build harness environment, pull down the specified version for the appropriate environment

Add yq to modules/vendor

---

modules/retag/Makefile
modules/retag/bin/process.sh
modules/yq/Makefile

This adds a function to the retag module that knows how to unpack chart bundles, add the sha256 tag to each image, and bundle them back up again.

Update chart tgzs with sha256 signatures

---

modules/pipeline-manifest/Makefile
modules/pipeline-manifest/bin/decorate-manifest.sh

This will create a manifest file parallel to our normal ones except they will have the additional attribute of image sha digest.  We postpone promotion of these files until we work out more details with the installer squad.

Add snapsha capability

---

modules/pipeline-manifest/Makefile
modules/pipeline-manifest/bin/parser.py

Run parallel versions so we can have a smooth transition

Update manifest schema to v2

---

modules/deploy/Makefile.bootstrap_openshift4

Adding a deploy module that uses github.com/open-cluster-management/bootstrap to create openshift clusters.

Adding a deploy module target for OpenShift 4.X via the bootstrap repo

---

modules/pipeline-manifest/Makefile

This reverts commit 999f0edc264ac97f2aa2bec018a4c88b3a2cc261.

Revert "pipeline: Update to work with OpenShift CI (#68)"

---

modules/sonar/Makefile

sonar: remove openshift ci targets
sonar: trim output lines from report.json

update sonar targets

---

modules/pipeline-manifest/Makefile

~[WIP] do not merge yet~
ready to merge

pipeline-manifest: add target to copy image from osci registry to quay

---

modules/pipeline-manifest/Makefile

Convenience target to run mirror and index; documented in the CICD build notes:
https://docs.google.com/document/d/1VTCZhVwNSA5V6i2dQiDXjX-426c4E1UqMZU9rT5czng/edit#heading=h.dm3g7kkvh7xr

mirror and index in one easy operation

---

modules/clusterpool/Makefile
modules/oc/Makefile

Reverts open-cluster-management/build-harness-extensions#92

Revert "Vendorize the Kubeconfig used in the oc module to prevent Kubeconfig polluiton."

---

modules/pipeline-manifest/Makefile
modules/pipeline-manifest/bin/build-index.sh

Implements optional tagging of all images during a hybrid build in order to enable canaries
Implements issue https://github.com/open-cluster-management/backlog/issues/4760

Test tag 4760

---

modules/clusterpool/Makefile
modules/oc/Makefile

From https://github.com/open-cluster-management/backlog/issues/7060 - add the ability to specify a token for `oc login`.  Still needs to be tested with an actual, working token.

Add token capability

---

modules/bootstrap-ks/Makefile

For https://github.com/open-cluster-management/backlog/issues/6668

Add functions for canary to use to get *KS kubeconfig and cleanup secret

---

.github/workflows/update-image-builder.yml

action: update update-image-builder [skip ci]

---

modules/bootstrap-ks/Makefile

Add interface to bootstrap-ks module `osd-aws`

Add osd-aws

---

modules/pipeline-manifest/Makefile
modules/pipeline-manifest/bin/_stealthy_mirror.py

Add ability to mirror without an errata

Add ability to mirror without an errata

---

modules/clusterpool/Makefile

Addresses issue [backlog/#19439](https://github.com/stolostron/backlog/issues/19439)

Move some selection logic inside the build harness for issue #19439

---

modules/sonar/Makefile

Double quotes and Double dollar signs were getting "$$Makefiled".

Fix Sonar variables

---

modules/sonar/Makefile

Signed-off-by: Chris Ahl <cahl@redhat.com>

forgot to save final change before commiting change

---

modules/oc/Makefile

Slack thread: https://coreos.slack.com/archives/CSZLMKPS5/p1660743123341969

Fix `curl` issue for `oc`

---

modules/pipeline-manifest/bin/_mirror-index.sh

Updating downstream with postgres13 integration.

Adding mapping for postgres13

---

modules/pipeline-manifest/bin/_mirror-index.sh

We're going with 1-72 tag so I updated that in indexing.

Updated postgres-13 sha to 1-72 registry tag

---

modules/pipeline-manifest/bin/_new-pipeline-operators.sh

Script for cutting new version branches in component operator repos.

Adapts _new-pipeline script for operator branches in _new-pipeline-operators script.

---

modules/pipeline-manifest/bin/_new-pipeline.sh

Removes edge branch from new pipeline branch-cutting automation.
Signed-off-by: Emily Macdonald <emmacdon@redhat.com>

Update new pipeline

---

modules/pipeline-manifest/bin/_backplane_mirror_index.sh

Updates backplane mirror index to exclude klusterlet-operator-bundle in mce 2.6 AND LATER.

Update _backplane_mirror_index.sh with klusterlet exclusions
